# Generated by Django 3.1.3 on 2020-11-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField(null=True)),
                ('popularity', models.FloatField(null=True)),
                ('revenue', models.IntegerField(null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('overview', models.TextField(null=True)),
                ('poster_path', models.CharField(max_length=500, null=True)),
                ('genres', models.ManyToManyField(to='game.Genre')),
            ],
        ),
    ]
